#spring:
#  application:
#    name: note
#  datasource:
#    url: jdbc:h2:file:./data/note;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#  h2:
#    console:
#      enabled: true  # Change this to 'enabled' instead of 'enable'
#  jpa:
#    hibernate:
#      ddl-auto: update  # This manages your schema
#    show-sql: true  # Optional: Show SQL queries in logs
spring:
  application:
    name: notes
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notes}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
